version: '3'
services:
  front:
    build:
      context: ./app-front
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - user-service
      - card-service
      - authentication-service
      - market-service
    networks:
      - APIGateway

  authentication-service:
    build:
        context: ./authentication-service
        dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - SERVER_PORT=80
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=card_database
      - DB_USERNAME=root
      - DB_PASSWORD=toto
    depends_on:
      - db
    networks:
      - APIGateway

  card-service:
    build:
      context: ./card-service
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - SERVER_PORT=80
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=card_database
      - DB_USERNAME=root
      - DB_PASSWORD=toto
    depends_on:
      - db
    networks:
      - APIGateway

  market-service:
    build:
      context: ./market-service
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      - SERVER_PORT=80
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=card_database
      - DB_USERNAME=root
      - DB_PASSWORD=toto
    depends_on:
      - db
    networks:
      - APIGateway

  user-service:
    build:
        context: ./user-service
        dockerfile: Dockerfile
    ports:
      - "8083:80"
    environment:
      - SERVER_PORT=80
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=card_database
      - DB_USERNAME=root
      - DB_PASSWORD=toto
    depends_on:
      - db
    networks:
      - APIGateway

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=card_database
      - MYSQL_ROOT_PASSWORD=toto
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
    ports:
      - "3306:3306"
#    volumes:
#      - ./data:/var/lib/mysql
    networks:
      - APIGateway

networks:
  APIGateway:
    driver: bridge

#    SELECT user, host FROM mysql.user WHERE user = 'user';
