version: '3'
services:
# ---------------------------- PROXY ----------------------------
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - front
    ports:
      - "80:80"
    networks:
      - APIGateway

# ---------------------------- FRONT ----------------------------
  front:
    build:
      context: ./app-front
      dockerfile: Dockerfile
    depends_on:
      - user-service
      - card-service
      - authentication-service
      - game-service
    networks:
      - APIGateway

# ---------------------------- SERVICES ----------------------------
  authentication-service:
    build:
        context: ./
        dockerfile: ./authentication-service/Dockerfile
    environment:
      - SERVER_PORT=80
      - DB_HOST=db-authentication
      - DB_PORT=3306
      - DB_NAME=authentication_database
      - DB_USERNAME=root
      - DB_PASSWORD=toto
    volumes:
      - maven-repo:/root/.m2
    depends_on:
      - db-authentication
    networks:
      - APIGateway

  card-service:
    build:
      context: ./
      dockerfile: ./card-service/Dockerfile
    environment:
      - SERVER_PORT=80
      - DB_HOST=db-card
      - DB_PORT=3306
      - DB_NAME=card_database
      - DB_USERNAME=root
      - DB_PASSWORD=toto
    volumes:
      - maven-repo:/root/.m2
    depends_on:
      - db-card
    networks:
      - APIGateway

  game-service:
    build:
      context: ./
      dockerfile: ./game-service/Dockerfile
    environment:
      - SERVER_PORT=80
      - DB_HOST=db-game
      - DB_PORT=3306
      - DB_NAME=game_database
      - DB_USERNAME=root
      - DB_PASSWORD=toto
    volumes:
      - maven-repo:/root/.m2
    depends_on:
      - db-game
    networks:
      - APIGateway

  user-service:
    build:
        context: ./
        dockerfile: ./user-service/Dockerfile
    environment:
      - SERVER_PORT=80
      - DB_HOST=db-user
      - DB_PORT=3306
      - DB_NAME=user_database
      - DB_USERNAME=root
      - DB_PASSWORD=toto
    volumes:
      - maven-repo:/root/.m2
    depends_on:
      - db-user
    networks:
      - APIGateway

# ---------------------------- DATABASES ----------------------------
  db-authentication:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=authentication_database
      - MYSQL_ROOT_PASSWORD=toto
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
    networks:
      - APIGateway

  db-card:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=card_database
      - MYSQL_ROOT_PASSWORD=toto
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
    networks:
      - APIGateway

  db-game:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=game_database
      - MYSQL_ROOT_PASSWORD=toto
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
    networks:
      - APIGateway

  db-user:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=user_database
      - MYSQL_ROOT_PASSWORD=toto
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
    networks:
      - APIGateway

networks:
  APIGateway:
    driver: bridge

volumes:
  maven-repo: